### ISSUE TITLE
zmq_dispatcher errors

### ISSUE THREAD

**Issue by rmsferreira** [MISP/misp-dashboard#48] opened 2018-03-15 16:58 UTC
I people

after a install the system and start  I have thies error:

ile "/var/www/misp-dashboard/zmq_dispatcher.py", line 282, in <module>
    main(args.sleeptime)
  File "/var/www/misp-dashboard/zmq_dispatcher.py", line 258, in main
    process_log(zmqName, content)
  File "/var/www/misp-dashboard/zmq_dispatcher.py", line 240, in process_log
    dico_action[topic](zmq_name, jsonevent)
  File "/var/www/misp-dashboard/zmq_dispatcher.py", line 214, in handler_attribute
    geo_helper.getCoordFromIpAndPublish(jsonattr['value'], jsonattr['category'])
  File "/var/www/misp-dashboard/helpers/geo_helper.py", line 106, in getCoordFromIpAndPublish
    self.push_to_redis_geo(self.keyCategRad, coord['lon'], coord['lat'], json.dumps(ordDic))
  File "/var/www/misp-dashboard/helpers/geo_helper.py", line 166, in push_to_redis_geo
    self.serv_redis_db.geoadd(keyname, lon, lat, content)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 2121, in geoadd
    return self.execute_command('GEOADD', name, *values)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 668, in execute_command
    return self.parse_response(connection, command_name, **options)
  File "/var/www/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/client.py", line 680, in parse_response
    response = connection.read_response()
  File "/var/www/misp-dashboard/DASHENV/lib/python3.5/site-packages/redis/connection.py", line 629, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'GEOADD'

**Comment by mokaddem** [comment] 2018-03-16 12:18
Hello,
Can you try the solution presented here #1 ?

**Comment by faustus25** [comment] 2018-08-30 19:26
Shouldn't be an issue in the latest commit.

If you are still on the same version do try the following:

**Comment by faustus25** [comment] 2018-08-30 19:29
Latest commit should have corrected this.

Older version required disabling serv_redis_db.geoadd in the function push_to_redis_geo
```
1
	def push_to_redis_geo(keyCateg, lon, lat, content):
2
	    now = datetime.datetime.now()
3
	    today_str = str(now.year)+str(now.month)+str(now.day)
4
	    keyname = "{}:{}".format(keyCateg, today_str)
5
	    #serv_redis_db.geoadd(keyname, lon, lat, `content)`
```

**Comment by adulau** [comment] 2018-10-01 07:11
Feel free to reopen if the issue is still present. It should have been fixed in recent versions.

**Closed by adulau** 2018-10-01 07:11 UTC
